"""initial migration

Revision ID: d09ee3b14014
Revises: 
Create Date: 2025-09-25 20:40:01.089883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09ee3b14014'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('notes_owner_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_owner_id_fkey'), 'notes', 'users', ['owner_id'], ['id'])
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
